import type { NextPage } from 'next'
import Head from 'next/head'
import Tabela from '../components/Tabela'
import LayOut from '../components/Layout'
import Cliente from '../core/Cliente'
import Botao from '../components/Botao'
import Formulario from '../components/Formulario'
import { useEffect, useState } from 'react'
import ClienteRepositorio from '../core/ClienteRepositorio'

const Home: NextPage = () => { 

  const repo: ClienteRepositorio = new ColecaoCliente()

  const [cliente, setCliente] = useState<Cliente>(Cliente.vazio)
  const [clientes, setClientes] = useState<Cliente>([])
  const [visivel, setVisivel] = useState<'tabela' | 'formulario'>('tabela')

  useEffect(() => {
    repo.obterTodos().then(setClientes)
  }, [])
 

  const clienteSelecionado = (cliente: Cliente) => {
    setCliente(cliente)
    setVisivel('formulario')
  }
  const clienteExcluido = (cliente: Cliente) => {
    console.log('Excluir', cliente.nome)
  }
  function salvarCliente(cliente: Cliente) {
    console.log(cliente)
    setVisivel('tabela')
   
  }
  function novoCliente() {
    setCliente(Cliente.vazio())
    setVisivel('formulario')
   
  }
  return (
    <div
      className={`flex justify-center items-center h-screen bg-gradient-to-r from-purple-500 to-blue-100 text-white`}
    >
      <Head>
        <title>Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <LayOut titulo='Cadastro Simples'>
        {visivel === 'tabela' ? (
          <>
            <div className='flex justify-end'>
              <Botao
                cor='green'
                className='mb-4'
                onClick={novoCliente}
              >
                Novo Cliente{' '}
              </Botao>
            </div>
            <Tabela
              clientes={clientes}
              clienteSelecionado={clienteSelecionado}
              clienteExcluido={clienteExcluido}
            />
          </>
        ) : (
          <Formulario
            clienteMudou={salvarCliente}
            cliente={cliente}
            cancelado={() => setVisivel('tabela')}
          />
        )}
      </LayOut>
    </div>
  )
}

export default Home
